feat(js-toolkit): RequireCapability: convert package.json version classfier to OSGi version classifer
liferay/liferay-frontend-projects pull request #257
Opened 2020-12-02 10:12 UTC by aschaeffer

Follow-up to PR #219

This PR also converts the version in the manifest header `RequireCapability`.

2020-12-02 14:06 UTC, wincent requested changes
@izaera: another one that could be replicated for 3.x?

2020-12-02 14:06 UTC, wincent commented on maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/index.js
> +}
So this is a near duplicate of [these lines](https://github.com/liferay/liferay-frontend-projects/blob/fc0a3cb5f972758db6277eb1c876a20a2e7b01b7/maintenance/projects/js-toolkit/packages/liferay-npm-bundler/src/jar/manifest.ts#L33-L39), so we should move this function to somewhere common where the same logic can be used by both places. The other instance of this already has test coverage too, as a bonus. Requesting changes @aschaeffer to get your thoughts on that.

2020-12-03 09:58 UTC, izaera commented
> another one that could be replicated for 3.x?

I would wait for the webpack 5 federation epic to finish before doing anything in bundler 3. Because it is very possible that we have to restructure it.

2020-12-09 11:11 UTC, wincent commented
lg2m. Let me just grab this and rebase it because CI is red but I believe it will be green with a rebase.

2020-12-09 11:38 UTC, wincent approved these changes

2020-12-09 11:47 UTC, merged

2020-12-09 12:19 UTC, wincent commented
Included [in v2.21.0 release](https://github.com/liferay/liferay-frontend-projects/releases/tag/liferay-js-toolkit%2Fv2.21.0).